/* This file is autogenerated*/
#ifndef __FMV_SUBS_H__
#define __FMV_SUBS_H__

#include "types.h"
#include "fmv_subs.h"
#include "rebirth_text.h"

const fmv_sub fmv_17[1] = {
    {
        TS_TO_FRAMES(0, 0, 0),
        (char*)NULL
    }
};

const fmv_sub fmv_18[1] = {
    {
        TS_TO_FRAMES(0, 0, 0),
        (char*)NULL
    }
};

const fmv_sub fmv_19[1] = {
    {
        TS_TO_FRAMES(0, 0, 0),
        (char*)NULL
    }
};

const fmv_entry fmv_table[3] = {
    {
        ARRAY_COUNT(fmv_17),
        fmv_17
    },
    {
        ARRAY_COUNT(fmv_18),
        fmv_18
    },
    {
        ARRAY_COUNT(fmv_19),
        fmv_19
    }
};

#endif /* __FMV_SUBS_H__ */
