/* This file is autogenerated*/
#ifndef __FMV_SUBS_H__
#define __FMV_SUBS_H__

#include "types.h"
#include "fmv_subs.h"
#include "rebirth_text.h"

const fmv_sub fmv_17[93] = {
    {
        TS_TO_FRAMES(0, 0, 0),
        (char*)NULL
    },
    {
        TS_TO_FRAMES(0, 27, 560),
        "Everyone, please listen to me."
    },
    {
        TS_TO_FRAMES(0, 29, 260),
        (char*)NULL
    },
    {
        TS_TO_FRAMES(0, 29, 900),
        "We, as Huma and Gajuma, were walking a path" NL
        "of coexistence as neighbors and good friends."
    },
    {
        TS_TO_FRAMES(0, 36, 840),
        (char*)NULL
    },
    {
        TS_TO_FRAMES(0, 38, 60),
        "Despite that, now we have begun fighting" NL
        "over the differences between our races..."
    },
    {
        TS_TO_FRAMES(0, 40, 820),
        (char*)NULL
    },
    {
        TS_TO_FRAMES(0, 41, 300),
        "...and for that reason alone."
    },
    {
        TS_TO_FRAMES(0, 44, 220),
        (char*)NULL
    },
    {
        TS_TO_FRAMES(0, 44, 800),
        "Things aren't that simple!"
    },
    {
        TS_TO_FRAMES(0, 46, 560),
        (char*)NULL
    },
    {
        TS_TO_FRAMES(0, 46, 820),
        "We're just trying to set things right!"
    },
    {
        TS_TO_FRAMES(0, 49, 280),
        (char*)NULL
    },
    {
        TS_TO_FRAMES(0, 50, 200),
        "Isn't the Queen supposed to be on our side?"
    },
    {
        TS_TO_FRAMES(0, 53, 240),
        (char*)NULL
    },
    {
        TS_TO_FRAMES(0, 54, 200),
        "What even is race?"
    },
    {
        TS_TO_FRAMES(0, 55, 740),
        (char*)NULL
    },
    {
        TS_TO_FRAMES(0, 56, 160),
        "Though we differ in appearance,"
    },
    {
        TS_TO_FRAMES(0, 58, 660),
        (char*)NULL
    },
    {
        TS_TO_FRAMES(0, 59, 180),
        "in times of joy we laugh. and in" NL
        "times of sorrow we shed tears."
    },
    {
        TS_TO_FRAMES(1, 2, 820),
        (char*)NULL
    },
    {
        TS_TO_FRAMES(1, 3, 360),
        "Why is that?"
    },
    {
        TS_TO_FRAMES(1, 4, 540),
        (char*)NULL
    },
    {
        TS_TO_FRAMES(1, 5, 500),
        "It is because our hearts are the same."
    },
    {
        TS_TO_FRAMES(1, 8, 300),
        (char*)NULL
    },
    {
        TS_TO_FRAMES(1, 8, 600),
        "Is that really the Queen?"
    },
    {
        TS_TO_FRAMES(1, 11, 540),
        (char*)NULL
    },
    {
        TS_TO_FRAMES(1, 12, 120),
        "This is what I believe" EM_DASH
    },
    {
        TS_TO_FRAMES(1, 13, 540),
        (char*)NULL
    },
    {
        TS_TO_FRAMES(1, 13, 540),
        "that the body is nothing more than" NL
        "a vessel which houses the heart."
    },
    {
        TS_TO_FRAMES(1, 18, 140),
        (char*)NULL
    },
    {
        TS_TO_FRAMES(1, 18, 800),
        "Even should there be a thing such as race" EM_DASH
    },
    {
        TS_TO_FRAMES(1, 20, 980),
        (char*)NULL
    },
    {
        TS_TO_FRAMES(1, 20, 980),
        EM_DASH "It is not \"Gajuma\" or \"Huma,\" but rather" NL
        "one " YELLOW "Mankind" WHITE " that shares this earth."
    },
    {
        TS_TO_FRAMES(1, 28, 220),
        (char*)NULL
    },
    {
        TS_TO_FRAMES(1, 29, 440),
        "I ask you all to remember..."
    },
    {
        TS_TO_FRAMES(1, 30, 720),
        (char*)NULL
    },
    {
        TS_TO_FRAMES(1, 30, 720),
        "We have all had times where we've shared" NL
        "laughter, tears, sorrow, and joy..."
    },
    {
        TS_TO_FRAMES(1, 37, 100),
        (char*)NULL
    },
    {
        TS_TO_FRAMES(1, 37, 720),
        "...Times where we have been treated with" NL
        "kindness."
    },
    {
        TS_TO_FRAMES(1, 39, 880),
        (char*)NULL
    },
    {
        TS_TO_FRAMES(1, 39, 880),
        "and times where we have eaten delicious" NL
        "food with one another..."
    },
    {
        TS_TO_FRAMES(1, 42, 160),
        (char*)NULL
    },
    {
        TS_TO_FRAMES(1, 44, 480),
        "I know of a village, where whenever one of the" NL
        "ladies bakes pies, everyone gathers together."
    },
    {
        TS_TO_FRAMES(1, 49, 400),
        (char*)NULL
    },
    {
        TS_TO_FRAMES(1, 53, 460),
        "It doesn't matter if they're Huma or Gajuma." NL
        "Everyone eats together and says \"How Delicious!\""
    },
    {
        TS_TO_FRAMES(1, 58, 320),
        (char*)NULL
    },
    {
        TS_TO_FRAMES(1, 58, 320),
        "Don't let her fool you! She's trying to" NL
        "win us over because she values her life!"
    },
    {
        TS_TO_FRAMES(2, 3, 160),
        (char*)NULL
    },
    {
        TS_TO_FRAMES(2, 6, 0),
        "I say this not because I fear death,"
    },
    {
        TS_TO_FRAMES(2, 8, 920),
        (char*)NULL
    },
    {
        TS_TO_FRAMES(2, 12, 20),
        "but because I believe that living when" NL
        "everyone you love hates one another"
    },
    {
        TS_TO_FRAMES(2, 15, 560),
        (char*)NULL
    },
    {
        TS_TO_FRAMES(2, 15, 560),
        "is a fate as cruel as death..."
    },
    {
        TS_TO_FRAMES(2, 19, 400),
        (char*)NULL
    },
    {
        TS_TO_FRAMES(2, 25, 780),
        "Your Majesty..."
    },
    {
        TS_TO_FRAMES(2, 26, 640),
        (char*)NULL
    },
    {
        TS_TO_FRAMES(2, 27, 600),
        "That's...not Agarte..."
    },
    {
        TS_TO_FRAMES(2, 29, 540),
        (char*)NULL
    },
    {
        TS_TO_FRAMES(2, 31, 260),
        "I want you to listen to my last request."
    },
    {
        TS_TO_FRAMES(2, 34, 920),
        (char*)NULL
    },
    {
        TS_TO_FRAMES(2, 38, 320),
        "If there is ever a time where you eat a" NL
        "pie...a peach pie..."
    },
    {
        TS_TO_FRAMES(2, 42, 400),
        (char*)NULL
    },
    {
        TS_TO_FRAMES(2, 43, 60),
        "I want you to close your eyes and think" NL
        "about this."
    },
    {
        TS_TO_FRAMES(2, 45, 580),
        (char*)NULL
    },
    {
        TS_TO_FRAMES(2, 48, 840),
        "In that heart of yours which" NL
        "finds it so delicious..."
    },
    {
        TS_TO_FRAMES(2, 51, 500),
        (char*)NULL
    },
    {
        TS_TO_FRAMES(2, 51, 500),
        "Is there such a thing as race?"
    },
    {
        TS_TO_FRAMES(2, 53, 360),
        (char*)NULL
    },
    {
        TS_TO_FRAMES(3, 9, 0),
        "Let's move!"
    },
    {
        TS_TO_FRAMES(3, 9, 640),
        (char*)NULL
    },
    {
        TS_TO_FRAMES(3, 12, 380),
        "Claire!!"
    },
    {
        TS_TO_FRAMES(3, 12, 960),
        (char*)NULL
    },
    {
        TS_TO_FRAMES(3, 13, 520),
        "Why you...!"
    },
    {
        TS_TO_FRAMES(3, 14, 600),
        (char*)NULL
    },
    {
        TS_TO_FRAMES(3, 16, 680),
        "Claire!!"
    },
    {
        TS_TO_FRAMES(3, 17, 400),
        (char*)NULL
    },
    {
        TS_TO_FRAMES(3, 18, 540),
        VEIGUE "!!"
    },
    {
        TS_TO_FRAMES(3, 19, 280),
        (char*)NULL
    },
    {
        TS_TO_FRAMES(3, 19, 380),
        "Move! Out of my way!"
    },
    {
        TS_TO_FRAMES(3, 21, 700),
        (char*)NULL
    },
    {
        TS_TO_FRAMES(3, 28, 940),
        VEIGUE "!!"
    },
    {
        TS_TO_FRAMES(3, 29, 920),
        (char*)NULL
    },
    {
        TS_TO_FRAMES(3, 29, 920),
        "Claire!!"
    },
    {
        TS_TO_FRAMES(3, 31, 680),
        (char*)NULL
    },
    {
        TS_TO_FRAMES(3, 46, 520),
        "Claire... You're Claire..."
    },
    {
        TS_TO_FRAMES(3, 48, 960),
        (char*)NULL
    },
    {
        TS_TO_FRAMES(3, 51, 280),
        "I always believed, that no" NL
        "matter what I looked like"
    },
    {
        TS_TO_FRAMES(3, 55, 850),
        (char*)NULL
    },
    {
        TS_TO_FRAMES(3, 55, 850),
        "you would come to realize that it was me..."
    },
    {
        TS_TO_FRAMES(3, 58, 80),
        (char*)NULL
    },
    {
        TS_TO_FRAMES(4, 0, 820),
        "Claire..."
    },
    {
        TS_TO_FRAMES(4, 1, 640),
        (char*)NULL
    }
};

const fmv_sub fmv_18[95] = {
    {
        TS_TO_FRAMES(0, 0, 0),
        (char*)NULL
    },
    {
        TS_TO_FRAMES(0, 6, 640),
        "The sky is beautiful..."
    },
    {
        TS_TO_FRAMES(0, 7, 900),
        (char*)NULL
    },
    {
        TS_TO_FRAMES(0, 10, 500),
        "Everything's over, isn't it?"
    },
    {
        TS_TO_FRAMES(0, 11, 920),
        (char*)NULL
    },
    {
        TS_TO_FRAMES(0, 12, 300),
        "Yeah..."
    },
    {
        TS_TO_FRAMES(0, 12, 920),
        (char*)NULL
    },
    {
        TS_TO_FRAMES(0, 14, 300),
        "I guess everything turned" NL
        "out okay in the end?"
    },
    {
        TS_TO_FRAMES(0, 16, 620),
        (char*)NULL
    },
    {
        TS_TO_FRAMES(0, 19, 80),
        "I am of the same mind."
    },
    {
        TS_TO_FRAMES(0, 21, 500),
        (char*)NULL
    },
    {
        TS_TO_FRAMES(0, 22, 120),
        "No, not just me, but everyone" NL
        "else as well."
    },
    {
        TS_TO_FRAMES(0, 25, 860),
        (char*)NULL
    },
    {
        TS_TO_FRAMES(0, 26, 440),
        "Thank you."
    },
    {
        TS_TO_FRAMES(0, 27, 120),
        (char*)NULL
    },
    {
        TS_TO_FRAMES(0, 29, 60),
        "Your Majesty!"
    },
    {
        TS_TO_FRAMES(0, 29, 820),
        (char*)NULL
    },
    {
        TS_TO_FRAMES(0, 31, 120),
        "Your Majesty! Your Majesty!!"
    },
    {
        TS_TO_FRAMES(0, 32, 760),
        (char*)NULL
    },
    {
        TS_TO_FRAMES(0, 33, 860),
        "I always knew...what would happen" NL
        "to this world because of me..."
    },
    {
        TS_TO_FRAMES(0, 41, 720),
        (char*)NULL
    },
    {
        TS_TO_FRAMES(0, 42, 280),
        "And yet... No matter what, I desired" NL
        "the body of a Huma..."
    },
    {
        TS_TO_FRAMES(0, 46, 800),
        (char*)NULL
    },
    {
        TS_TO_FRAMES(0, 47, 280),
        "Why... Why was that?"
    },
    {
        TS_TO_FRAMES(0, 48, 860),
        (char*)NULL
    },
    {
        TS_TO_FRAMES(0, 49, 400),
        "But...I've finally come to realize" NL
        "what is really important..."
    },
    {
        TS_TO_FRAMES(0, 54, 540),
        (char*)NULL
    },
    {
        TS_TO_FRAMES(0, 55, 120),
        "At least...as the ruler of this kingdom..."
    },
    {
        TS_TO_FRAMES(0, 58, 660),
        (char*)NULL
    },
    {
        TS_TO_FRAMES(0, 58, 660),
        "I was able to do this one thing..." NL
        "for the sake of " YELLOW "Mankind" WHITE "."
    },
    {
        TS_TO_FRAMES(1, 0, 860),
        (char*)NULL
    },
    {
        TS_TO_FRAMES(1, 1, 500),
        "Please, hang in there!"
    },
    {
        TS_TO_FRAMES(1, 2, 800),
        (char*)NULL
    },
    {
        TS_TO_FRAMES(1, 3, 0),
        "I'm sorry...for having caused" NL
        "trouble until the end..."
    },
    {
        TS_TO_FRAMES(1, 7, 0),
        (char*)NULL
    },
    {
        TS_TO_FRAMES(1, 7, 580),
        "I leave this nation...in your hands..."
    },
    {
        TS_TO_FRAMES(1, 9, 720),
        (char*)NULL
    },
    {
        TS_TO_FRAMES(1, 10, 620),
        "How could I rule without you?!"
    },
    {
        TS_TO_FRAMES(1, 12, 560),
        (char*)NULL
    },
    {
        TS_TO_FRAMES(1, 13, 120),
        "So long as you're there, it will be fine...."
    },
    {
        TS_TO_FRAMES(1, 15, 360),
        (char*)NULL
    },
    {
        TS_TO_FRAMES(1, 15, 640),
        "No..."
    },
    {
        TS_TO_FRAMES(1, 17, 40),
        (char*)NULL
    },
    {
        TS_TO_FRAMES(1, 18, 220),
        "Please live..."
    },
    {
        TS_TO_FRAMES(1, 19, 160),
        (char*)NULL
    },
    {
        TS_TO_FRAMES(1, 19, 880),
        "For my sake..."
    },
    {
        TS_TO_FRAMES(1, 21, 620),
        (char*)NULL
    },
    {
        TS_TO_FRAMES(1, 22, 300),
        "Agarte..."
    },
    {
        TS_TO_FRAMES(1, 23, 420),
        (char*)NULL
    },
    {
        TS_TO_FRAMES(1, 24, 340),
        "Milhaust..."
    },
    {
        TS_TO_FRAMES(1, 25, 540),
        (char*)NULL
    },
    {
        TS_TO_FRAMES(1, 25, 800),
        "I've always...loved you..."
    },
    {
        TS_TO_FRAMES(1, 29, 680),
        (char*)NULL
    },
    {
        TS_TO_FRAMES(1, 35, 880),
        "Agarte..."
    },
    {
        TS_TO_FRAMES(1, 36, 860),
        (char*)NULL
    },
    {
        TS_TO_FRAMES(2, 35, 60),
        "The conflicts between the races are still ongoing."
    },
    {
        TS_TO_FRAMES(2, 37, 300),
        (char*)NULL
    },
    {
        TS_TO_FRAMES(2, 38, 760),
        "This hatred and sorrow isn't going to" NL
        "disappear any time soon."
    },
    {
        TS_TO_FRAMES(2, 42, 340),
        (char*)NULL
    },
    {
        TS_TO_FRAMES(2, 42, 940),
        "But, we need to be able to overcome that..."
    },
    {
        TS_TO_FRAMES(2, 46, 420),
        (char*)NULL
    },
    {
        TS_TO_FRAMES(2, 46, 800),
        "So that this nation...can experience a " CYAN "rebirth" WHITE "."
    },
    {
        TS_TO_FRAMES(2, 49, 560),
        (char*)NULL
    },
    {
        TS_TO_FRAMES(2, 50, 80),
        YELLOW "Mankind" WHITE " will have to build relationships anew."
    },
    {
        TS_TO_FRAMES(2, 54, 520),
        (char*)NULL
    },
    {
        TS_TO_FRAMES(2, 54, 920),
        "It will likely take time, but it can be done."
    },
    {
        TS_TO_FRAMES(2, 57, 700),
        (char*)NULL
    },
    {
        TS_TO_FRAMES(2, 58, 0),
        "Yes, I agree."
    },
    {
        TS_TO_FRAMES(3, 0, 340),
        (char*)NULL
    },
    {
        TS_TO_FRAMES(3, 0, 940),
        "A time will come where everyone will" NL
        "see eye to eye. Just like we have."
    },
    {
        TS_TO_FRAMES(3, 6, 0),
        (char*)NULL
    },
    {
        TS_TO_FRAMES(3, 6, 300),
        "We are all one " YELLOW "Mankind" WHITE "."
    },
    {
        TS_TO_FRAMES(3, 8, 360),
        (char*)NULL
    },
    {
        TS_TO_FRAMES(3, 9, 20),
        "When everyone's hearts came together" NL
        "as one during that disaster,"
    },
    {
        TS_TO_FRAMES(3, 13, 300),
        (char*)NULL
    },
    {
        TS_TO_FRAMES(3, 13, 660),
        "I'm sure everyone all over the world realized that."
    },
    {
        TS_TO_FRAMES(3, 16, 480),
        (char*)NULL
    },
    {
        TS_TO_FRAMES(3, 21, 360),
        "A nation " CYAN "reborn" WHITE "..."
    },
    {
        TS_TO_FRAMES(3, 22, 960),
        (char*)NULL
    },
    {
        TS_TO_FRAMES(3, 23, 340),
        "I wonder what it'll be like."
    },
    {
        TS_TO_FRAMES(3, 24, 780),
        (char*)NULL
    },
    {
        TS_TO_FRAMES(3, 28, 540),
        "At the very least, I'd like to imagine it's" NL
        "a world where I don't have to wear this anymore."
    },
    {
        TS_TO_FRAMES(3, 34, 240),
        (char*)NULL
    },
    {
        TS_TO_FRAMES(3, 41, 200),
        "Are you willing to lend me a hand?"
    },
    {
        TS_TO_FRAMES(3, 43, 520),
        (char*)NULL
    },
    {
        TS_TO_FRAMES(3, 48, 880),
        "We might have different ways of getting there,"
    },
    {
        TS_TO_FRAMES(3, 50, 780),
        (char*)NULL
    },
    {
        TS_TO_FRAMES(3, 50, 780),
        "but we all have the same goal, right?"
    },
    {
        TS_TO_FRAMES(3, 53, 220),
        (char*)NULL
    },
    {
        TS_TO_FRAMES(3, 53, 960),
        YELLOW "Mankind" WHITE " will follow whatever path you choose."
    },
    {
        TS_TO_FRAMES(3, 56, 500),
        (char*)NULL
    },
    {
        TS_TO_FRAMES(3, 57, 280),
        "I feel like we can help guide" NL
        "them along the way."
    },
    {
        TS_TO_FRAMES(4, 1, 360),
        (char*)NULL
    },
    {
        TS_TO_FRAMES(4, 4, 700),
        "I know we can do it."
    },
    {
        TS_TO_FRAMES(4, 7, 320),
        (char*)NULL
    }
};

const fmv_sub fmv_19[29] = {
    {
        TS_TO_FRAMES(0, 0, 0),
        (char*)NULL
    },
    {
        TS_TO_FRAMES(1, 2, 720),
        "Your Majesty!"
    },
    {
        TS_TO_FRAMES(1, 3, 460),
        (char*)NULL
    },
    {
        TS_TO_FRAMES(1, 9, 380),
        "Your Majesty, you mustn't do this!"
    },
    {
        TS_TO_FRAMES(1, 11, 540),
        (char*)NULL
    },
    {
        TS_TO_FRAMES(1, 11, 540),
        "If you keep using your Force, then you'll..."
    },
    {
        TS_TO_FRAMES(1, 13, 220),
        (char*)NULL
    },
    {
        TS_TO_FRAMES(1, 24, 220),
        "Your Majesty!!"
    },
    {
        TS_TO_FRAMES(1, 25, 580),
        (char*)NULL
    },
    {
        TS_TO_FRAMES(2, 19, 380),
        VEIGUE "!"
    },
    {
        TS_TO_FRAMES(2, 20, 20),
        (char*)NULL
    },
    {
        TS_TO_FRAMES(2, 20, 20),
        "Stay away!"
    },
    {
        TS_TO_FRAMES(2, 20, 640),
        (char*)NULL
    },
    {
        TS_TO_FRAMES(2, 21, 940),
        "Claire, get out of here!"
    },
    {
        TS_TO_FRAMES(2, 23, 240),
        (char*)NULL
    },
    {
        TS_TO_FRAMES(2, 24, 40),
        "But..."
    },
    {
        TS_TO_FRAMES(2, 24, 660),
        (char*)NULL
    },
    {
        TS_TO_FRAMES(2, 24, 660),
        "Run, Claire...!"
    },
    {
        TS_TO_FRAMES(2, 25, 900),
        (char*)NULL
    },
    {
        TS_TO_FRAMES(2, 37, 360),
        "Claire!!"
    },
    {
        TS_TO_FRAMES(2, 39, 280),
        (char*)NULL
    },
    {
        TS_TO_FRAMES(3, 29, 600),
        "Who is it?"
    },
    {
        TS_TO_FRAMES(3, 30, 240),
        (char*)NULL
    },
    {
        TS_TO_FRAMES(3, 30, 800),
        "Hiya, " VEIGUE ". I'm " MAO "."
    },
    {
        TS_TO_FRAMES(3, 33, 0),
        (char*)NULL
    },
    {
        TS_TO_FRAMES(3, 33, 540),
        "I'm " EUGENE " Gallardo."
    },
    {
        TS_TO_FRAMES(3, 35, 400),
        (char*)NULL
    },
    {
        TS_TO_FRAMES(3, 36, 320),
        VEIGUE " Lungberg, we've come for you."
    },
    {
        TS_TO_FRAMES(3, 39, 920),
        (char*)NULL
    }
};

const fmv_entry fmv_table[3] = {
    {
        ARRAY_COUNT(fmv_17),
        fmv_17
    },
    {
        ARRAY_COUNT(fmv_18),
        fmv_18
    },
    {
        ARRAY_COUNT(fmv_19),
        fmv_19
    }
};

#endif /* __FMV_SUBS_H__ */
