.relativeinclude on
.include "slps.asm"
.include "btl.asm"
.include "3dfield.asm"
.include "12406.asm"
.include "00014.asm"
.include "mnu_name.asm"
.include "mnu_status.asm"
.include "mnu_monster.asm"