
# Include directories
EE_INCS := -I. $(EE_INCS)

# Optimization compiler flags
EE_C_OPTFLAGS ?= -O0
EE_CXX_OPTFLAGS ?= -O0

# Warning compiler flags
EE_WARNFLAGS ?= -Wall

# C compiler flags
EE_CFLAGS := -D_EE -G0 $(EE_C_OPTFLAGS) $(EE_WARNFLAGS) $(EE_DBGINFOFLAGS) $(EE_CFLAGS)

# C++ compiler flags
EE_CXXFLAGS := -D_EE -G0 $(EE_CXX_OPTFLAGS) $(EE_WARNFLAGS) $(EE_DBGINFOFLAGS) $(EE_CXXFLAGS)

# Command for ensuring the output directory for the rule exists.
DIR_GUARD = @$(MKDIR) -p $(@D)

$(BUILD_DIR)/%.o: $(SRC_DIR)/%.c makefile
	$(DIR_GUARD)
	$(EE_CC) $(EE_CFLAGS) $(EE_INCS) -MMD -MP -c $< -o $@

$(BUILD_DIR)/%.o: $(SRC_DIR)/%.cpp makefile
	$(DIR_GUARD)
	$(EE_CXX) $(EE_CXXFLAGS) $(EE_INCS) -MMD -MP -c $< -o $@

$(EE_LIB): $(EE_OBJS)
	$(DIR_GUARD)
	$(EE_AR) cru $(EE_LIB) $(EE_OBJS)